---
title: Ayuda y recursos para el aprendizaje de R (actualizado)
author: Rubén Fernández Casal
date: '2023-03-23'
slug: ayuda-y-recursos-para-el-aprendizaje-de-r
categories:
  - R
tags:
  - Apuntes
summary: "Listado de recursos para el aprendizaje de R y la obtención de ayuda."
output:
  blogdown::html_page:
    toc: true
---

A continuación se muestran algunos recursos que considero que pueden ser útiles para el aprendizaje de R y la obtención de ayuda... (página en preparación...).


## Ayuda online

- Ayuda en línea sobre funciones o paquetes: [rdrr.io](https://rdrr.io/),  [RDocumentation](https://www.rdocumentation.org/)

- Buscador [RSeek](http://rseek.org/)

- [StackOverflow](http://stackoverflow.com/questions/tagged/r), [en castellano](https://es.stackoverflow.com/questions/tagged/r)

- [Cross Validated](https://stats.stackexchange.com)


## Cursos

Algunos cursos gratuitos:
   
- [Coursera](https://www.coursera.org/):

    - [Introducción a Data Science: Programación Estadística con  R](https://www.coursera.org/learn/intro-data-science-programacion-estadistica-r)

    - [Mastering Software Development in R](https://www.coursera.org/specializations/r)

<!-- -->

- [DataCamp](https://www.datacamp.com/courses):

    - [Introducción a R](https://www.datacamp.com/courses/introduccion-a-r/)
  
<!-- -->
  
- [Stanford online](http://online.stanford.edu/courses):

    - [Statistical Learning](http://online.stanford.edu/course/statistical-learning)
  
<!-- -->

- Curso UCA: [Introducción a R, R-commander y shiny](http://knuth.uca.es/moodle/course/view.php?id=51)

<!-- -->

- Curso [R CODER](https://r-coder.com/curso-r)

<!-- -->

- Udacity: [Data Analysis with R](https://eu.udacity.com/course/data-analysis-with-r--ud651)

<!-- -->

- [Cognitive class](https://cognitiveclass.ai/courses?topic%5B%5D=r-programming):

    - [R for Data Science](https://cognitiveclass.ai/courses/r-101)


Incluso se pueden hacer cursos desde el propio R con el paquete [swirl](https://swirlstats.com).
Un listado de los cursos disponibles se puede consultar aquí:
[Swirl Courses](https://swirlstats.com/scn/title.html).  

Para información sobre cursos en castellano se puede recurrir a la web de [R-Hispano](http://r-es.org/) en el apartado [formación](http://r-es.org/category/formacion). Algunos de los cursos que aparecen en entradas antiguas son gratuitos. 
Ver: [Cursos MOOC relacionados con R](http://r-es.org/2016/02/12/cursos-masivos-y-otra-formacion-on-line-sobre-r/).


## Libros

A continuación se muestra una selección de libros (muchos en abierto) que considero que pueden resultar de utilidad.
Para referencias adicionales recomiendo ver el libro:

- Baruffa, O. (2022). *[Big Book of R](https://www.bigbookofr.com)*: Your last-ever bookmark (hopefully...).


### Iniciación a la programación en R

- Matloff, N. (2011). *The art of R programming: A tour of statistical software design*, [No Starch Press](https://www.nostarch.com/artofr.htm).

- Wickham, H., y Grolemund, G. (2016). *[R for data science: import, tidy, transform, visualize, and model data](http://r4ds.had.co.nz)*, [online-castellano](https://es.r4ds.hadley.nz), [O'Reilly](http://shop.oreilly.com/product/0636920034407.do).

- Grolemund, G. (2014). *[Hands-on programming with R: Write your own functions and simulations](https://rstudio-education.github.io/hopr)*, [O'Reilly](http://shop.oreilly.com/product/0636920028574.do).


### Programación avanzada en R

- Chambers, J.M. (2008). *Software for data analysis: programming with R*, [Springer](http://www.springer.com/la/book/9780387759357).

- Wickham, H. (2019). *[Advanced R, 2ª edición](https://adv-r.hadley.nz/)*, [Chapman & Hall](https://www.amazon.com/dp/0815384572), [1ª edición.](http://adv-r.had.co.nz/).

- Wickham, H. (2015). *[R packages: organize, test, document, and share your code](http://r-pkgs.had.co.nz/)* (actualmente 2ª edición en desarrollo con H. Bryan), [O'Reilly, 1ª edición](http://shop.oreilly.com/product/0636920034421.do).


### Bookdown

El paquete [Bookdown](https://bookdown.org) de R permite escribir libros empleando 
[R Markdown](http://rmarkdown.rstudio.com) y compartirlos. 
En https://bookdown.org está disponible una selección de libros escritos con este paquete.
En el [listado completo]((https://bookdown.org/home/archive/)) se incluyen muchos más (algunos en castellano).

Además de los anteriormente citados, podríamos destacar:

- Regresión y aprendizaje estadístico:

    - Kuhn, M., y Silge, J. (2022). *[Tidy Modeling with R](https://www.tmwr.org)*, [O'Reilly](https://www.oreilly.com/library/view/tidy-modeling-with/9781492096474).

- Datos temporales y espaciales:

    - Hyndman, R.J., y Athanasopoulos, G. (2021). *[Forecasting: principles and practice](https://otexts.com/fpp3)*. [OTexts](https://www.amazon.es/dp/0987507133).

    - Lovelace, R., Nowosad, J., y Muenchow, J. (2019). *[Geocomputation with R](https://geocompr.robinlovelace.net)*. [CRC](https://www.routledge.com/9781138304512).
    
    - Moraga, P. (2019). *[Geospatial health data: Modeling and visualization with R-INLA and shiny](https://www.paulamoraga.com/book-geospatial)*, [CRC](https://www.routledge.com/9780367357955).
        
    - Pebesma, E., y Bivand, R. (2021). *[Spatial Data Science](https://keen-swartz-3146c4.netlify.app)*.


Entre los disponibles en castellano:

- Fernández-Casal R., Roca-Pardiñas J., Costa J., y Oviedo de la Fuente, M. (2022). *[Introducción al Análisis de Datos con R](https://rubenfcasal.github.io/intror)*. [github](https://github.com/rubenfcasal/intror).

- Fernández-Casal R. y Cotos-Yáñez T.R. (2021). *[Estadística Espacial con R](https://rubenfcasal.github.io/estadistica_espacial)*. [github](https://github.com/rubenfcasal/estadistica_espacial). 

- Fernández-Casal R., Cao R. y Costa J. (2023). *[Técnicas de Simulación y Remuestreo](https://rubenfcasal.github.io/simbook)*  ([github](https://github.com/rubenfcasal/simbook)). La anterior edición (Fernández-Casal R. y Cao R., 2022, *Simulación Estadística*) está disponible en la rama *[primera_edicion](https://github.com/rubenfcasal/simbook/tree/primera_edicion)*.

- Cao R. y Fernández-Casal R. (2021). *[Técnicas de Remuestreo](https://rubenfcasal.github.io/book_remuestreo)*. [github](https://github.com/rubenfcasal/book_remuestreo).

- Fernández-Casal R., Costa J. y Oviedo de la Fuente, M. (2021). *[Aprendizaje Estadístico](https://rubenfcasal.github.io/aprendizaje_estadistico)*. [github](https://github.com/rubenfcasal/aprendizaje_estadistico).

- López-Taboada G. y Fernández-Casal R. (2020). *[Prácticas de Tecnologías de Gestión y Manipulación de Datos](https://gltaboada.github.io/tgdbook)*. [github](https://github.com/gltaboada/tgdbook).

- Fernández-Casal R. y Cotos-Yáñez T.R. (2018). *[Escritura de libros con bookdown](https://rubenfcasal.github.io/bookdown_intro)*,   [github](https://github.com/rubenfcasal/bookdown_intro). Incluye un apéndice con una [Introducción a RMarkdown](https://rubenfcasal.github.io/bookdown_intro/rmarkdown.html). 
    
- Gil Bellosta C.J. (2018). *[R para profesionales de los datos: una introducción](https://www.datanalytics.com/libro_r/index.html)*.

- Quintela del Rio A. (2019). *[Estadística Básica Edulcorada](https://bookdown.org/aquintela/EBE)*.


## Material online

En la web se puede encontrar mucho material adicional, por ejemplo:

- [CRAN: Other R documentation](https://www.r-project.org/other-docs.html)

- [RStudio](https://www.rstudio.com): 

    - [Online learning](https://www.rstudio.com/online-learning), 
      [Webinars](https://resources.rstudio.com/webinars)
      
    - [tidyverse](https://www.tidyverse.org):
      [dplyr](https://dplyr.tidyverse.org),
      [ggplot2](https://ggplot2.tidyverse.org),
      [tibble](https://tibble.tidyverse.org),
      [tidyr](https://tidyr.tidyverse.org),
      [stringr](https://stringr.tidyverse.org),
      [readr](https://readr.tidyverse.org),
      [purrr](https://purrr.tidyverse.org).
      
    - [RMarkdown](https://rmarkdown.rstudio.com), [shiny](http://shiny.rstudio.com), [sparklyr](https://spark.rstudio.com)

    - [CheatSheets](https://resources.rstudio.com/rstudio-cheatsheets) [github](https://github.com/rstudio/cheatsheets):
      [RMarkdown](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf),
      [Shiny](https://github.com/rstudio/cheatsheets/raw/master/shiny.pdf),
      [dplyr](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf),
      [tidyr](https://github.com/rstudio/cheatsheets/raw/master/data-import.pdf),
      [stringr](https://github.com/rstudio/cheatsheets/raw/master/stringr-cheat-sheet.pdf).

- [Microsoft R Application Network](https://mran.microsoft.com): [Getting Started with R](https://mran.microsoft.com/documents/getting-started)

- Blogs en inglés:

    - https://www.r-bloggers.com/

    - https://www.littlemissdata.com/blog/rstudioconf2019 
    
    - RStudio: https://blog.rstudio.com
    
    - Microsoft Revolutions: https://blog.revolutionanalytics.com


- Blogs en castellano:

    -  https://www.datanalytics.com
    
    -  http://oscarperpinan.github.io/R
  
    -  http://rubenfcasal.github.io
   
   
- Listas de correo:

    - Listas de distribución de r-project.org: 
    
        https://stat.ethz.ch/mailman/listinfo
    
    <!-- - Búsqueda en R-help:
    
        http://r.789695.n4.nabble.com/R-help-f789696.html -->    
    
    - Búsqueda en R-help-es: 
    
        https://r-help-es.r-project.narkive.com
      
        <!-- https://grokbase.com/g/r/r-help-es -->

    - Archivos de R-help-es: 
    
        https://stat.ethz.ch/pipermail/r-help-es

    
    
Si conoces algún otro recurso de interés no dudes en colaborar,
puedes enviar un correo a [rubenfcasal@gmail.com](mailto:rubenfcasal@gmail.com).

